brightness: 100

sleep:
  dim_brightness: 10
  dim_timeout: 600
  sleep_timeout: 86400

wallpaper:
  path: "mymedia/wallpapers/valley.png"
  quality: 30
  magnify: 100
  dithering: yes

system_buttons:
  $page.back:
    position: 11
  $page.previous:
    position: 12
  $page.next:
    position: 13

presets:
  $nav:
    icon_background_color: "transparent"
    icon_border_radius: 12
    icon_border_width: 4
    icon_border_size: 128
    icon_border_color: "FFFFFF"
    icon_size: 120
    icon_padding: 0
    icon_offset: 0,0
    icon_brightness: 99
    icon_color: "FFFFFF"
  room_folder:
    icon_border_width: 4
    icon_border_color: "FFFFFF"
    icon_border_size: 128
    icon_color: "FFFFFF"
    icon_background_color: "transparent"
    icon_size: 126
    icon_border_radius: 12
    icon_offset: 0,0  
    icon_padding: 0
  host_folder:
    icon_border_width: 4
    icon_border_color: "EEA0A9"
    icon_border_size: 128
    icon_color: "FFFFFF"
    icon_background_color: "transparent"
    icon_size: 126
    icon_border_radius: 12
    icon_offset: 0,0  
    icon_padding: 0
  base_button:
    icon_background_color: "transparent"
    icon_size: 128
    icon_border_radius: 12
    icon_color: "FFFFFF"
  cmd_button:
    icon_background_color: "transparent"
    icon_size: 128
    icon_border_radius: 12
    icon_color: "FFFFFF"
    text_color: "00FF00"
    text_align: "center"
    text_font: "dustismo_bold.ttf"
    text_size: 50
    text_offset: 0,0 
  settings_folder:
    icon_border_width: 4
    icon_border_color: "44EB22"
    icon_border_size: 128
    icon_color: "FFFFFF"
    icon_background_color: "transparent"
    icon_size: 126
    icon_border_radius: 12
    icon_offset: 0,0  
    icon_padding: 0
  light_off:
    icon: mdi:lightbulb-outline
    icon_background_color: "transparent"
    icon_color: "333333"
  light_on:
    icon: mdi:lightbulb
    icon_background_color: "transparent"
    icon_color: "FFD700"

pages:
  $root:
    wallpaper:
      path: "mymedia/wallpapers/neige.png"
      quality: 60
      magnify: 100
      dithering: yes
    buttons:
      - name: "Salon"
        presets: [room_folder]
        icon: mdi:sofa
        tap_action:
          action: $page.go_to
          data: "salon"
      - name: "cuisine"
        presets: [room_folder]
        icon: mdi:chef-hat
        tap_action:
          action: $page.go_to
          data: "cuisine"
      - name: "chambre"
        presets: [room_folder]
        icon: mdi:bed
        tap_action:
          action: $page.go_to
          data: "chambre"
      - name: ""
      - name: ""     
      - name: "Debian PC"
        presets:
          - host_folder
        icon: mdi:server-minus
        tap_action:
          action: $page.go_to
          data: debian_pc
      - name: "Debian miniPC"
        presets:
          - host_folder
        icon: mdi:server-minus
        tap_action:
          action: $page.go_to
          data: debian_minipc
      - name: "VidéoProj"
        presets:
          - host_folder
        icon: mdi:projector
        tap_action:
          action: $page.go_to
          data: video_projector
      - name: "pi4"
        presets:
          - host_folder
        icon: mdi:raspberry-pi
        tap_action:
          action: $page.go_to
          data: pi4
      - name: "Apps"
        presets: [room_folder]
        icon: mdi:apps
        tap_action:
          action: $page.go_to
          data: apps
      - name: ""
      - name: "settings"
        presets:
          - settings_folder
        icon: mdi:cog
        tap_action:
          action: $page.go_to
          data: settings
  salon:
    buttons:
      - name: "Temperature"
        entity_id: sensor.tz3000_utwgoauk_snzb_02_temperature
        presets: [cmd_button,base_button]
      - name: "Lampe droite"
        entity_id: light.lampe_droite
        presets: [base_button]
        tap_action:
          action: light.toggle
        hold_action:
          action: light.toggle
        longhold_action:
          action: light.toggle
        released_action:
          action: light.toggle
        states:
          "on":
            name: "LD ON"
            presets: [light_on]
          "off":
            name: "LD OFF"
            presets: [light_off]
      - name: "Lampe gauche"
        entity_id: light.lampe_gauche
        presets: [base_button]
        tap_action:
          action: light.toggle
        states:
          "on":
            name: "LG ON"
            presets: [light_on]
          "off":
            name: "LG OFF"
            presets: [light_off]
      - name: "Lampe escalier"
        entity_id: light.lampe_escalier
        presets: [base_button]
        tap_action:
          action: light.toggle
        states:
          "on":
            name: "LE ON"
            presets: [light_on]
          "off":
            name: "LE OFF"
            presets: [light_off]
      - name: "Écrans Salon"
        entity_id: script.eteint_les_ecrans_du_salon
        presets: [base_button]
        icon: mdi:monitor
        tap_action:
          action: script.eteint_les_ecrans_du_salon
  cuisine:
    buttons:
      - name: "Néon du fond"
        entity_id: switch.er_lu_kai_guan_switch_1
        presets: [base_button]
        tap_action:
          action: switch.toggle
        states:
          "on":
            name: "NF ON"
            presets:
              - light_on
          "off":
            name: "NF OFF"
            presets:
              - light_off

      - name: "Néon droite"
        entity_id: switch.er_lu_kai_guan_switch_2
        presets:
          - base_button
        tap_action:
          action: switch.toggle
        states:
          "on":
            name: "ND ON"
            presets:
              - light_on
          "off":
            name: "ND OFF"
            presets:
              - light_off
  chambre:
    buttons:
      - name: "Temperature chambre"
        entity_id: sensor.tz3000_utwgoauk_snzb_02_temperature
        presets: [cmd_button,base_button]
      - name: "Lampe droite de la chambre"
        entity_id: light.lampe_droite_de_la_chambre
        presets:
          - base_button
        tap_action:
          action: light.toggle
        states:
          "on":
            name: "LDG ON"
            presets:
              - light_on
          "off":
            name: "LDG OFF"
            presets:
              - light_off
      - name: "Lampe gauche de la chambre"
        entity_id: light.lampe_gauche_de_la_chambre
        presets: [base_button]
        tap_action:
          action: light.toggle
        states:
          "on":
            name: "LDG ON"
            presets:
              - light_on
          "off":
            name: "LDG OFF"
            presets:
              - light_off
  debian_pc:
    buttons:
      - name: "reboot"
        entity_id: script.reboot_debian_pc
        presets:
          - base_button
        icon: mdi:restart
        tap_action:
          action: script.reboot_debian_pc
      - name: "poweroff"
        entity_id: script.power_off_debian_pc
        presets:
          - base_button

        icon: mdi:power
        tap_action:
          action: script.power_off_debian_pc 
                       
  debian_minipc:
    buttons:
      - name: "reboot"
        entity_id: script.reboot_minipc_server
        presets:
          - base_button
        icon: mdi:restart
        tap_action:
          action: script.reboot_minipc_server
      - name: "poweroff"
        entity_id: script.power_off_minipc_server
        presets:
          - base_button
        icon: mdi:power
        tap_action:
          action: script.power_off_minipc_server
  video_projector:
    buttons:
      - name: "reboot"
        entity_id: script.reboot_rpi5
        presets:
          - base_button
        icon: mdi:restart
        tap_action:
          action: script.reboot_rpi5
      - name: "poweroff"
        entity_id: script.power_off_rpi5
        presets:
          - base_button
        icon: mdi:power
        tap_action:
          action: script.power_off_rpi5
  pi4:
    buttons:
      - name: "reboot"
        entity_id: script.reboot_rpi4
        presets:
          - base_button
        icon: mdi:restart
        tap_action:
          action: script.reboot_rpi4
      - name: "poweroff"
        entity_id: script.power_off_rpi4
        presets:
          - base_button
        icon: mdi:power
        tap_action:
          action: script.power_off_rpi4
  settings:
    buttons:
      - name: "RAM cache"
        presets: [cmd_button]
        icon: mdi:memory
        tap_action:
          action: $cmd.exec_text
          data:
            cmd: "assets/scripts/clear_cache_ram.sh --text"
            trim: no
            max_len: 32
        longhold_action:
          actions:
            - action: $cmd.exec
              data:
                cmd: "assets/scripts/clear_cache_ram.sh --clear"
            - action: $cmd.text_clear
      - name: "DISK cache"
        presets: [cmd_button]
        icon: mdi:database
        tap_action:
          action: $cmd.exec_text
          data:
            cmd: "assets/scripts/clear_cache.sh --text"
            trim: no
            max_len: 32
        longhold_action:
          actions:
            - action: $cmd.exec
              data:
                cmd: "assets/scripts/clear_cache.sh --clear"
            - action: $cmd.text_clear
      - name: "Clock"
        presets: [cmd_button]
        icon: mdi:clock-outline
        tap_action:
          action: $cmd.poll_start
        hold_action:
          action: $cmd.poll_stop
        poll:
          every_ms: 1000
          action:
            action: $cmd.exec_text
            data:
              cmd: "assets/scripts/clock_now.sh"
              trim: yes
              max_len: 32
      - name: "CPU"
        presets: [cmd_button]
        icon: mdi:cpu-64-bit
        tap_action:
          action: $cmd.poll_start
        hold_action:
          action: $cmd.poll_stop
        poll:
          every_ms: 2000
          action:
            action: $cmd.exec_text
            data:
              cmd: "assets/scripts/cpu_usage.sh"
              trim: yes
              max_len: 32
      - name: "RAM"
        presets: [cmd_button]
        icon: mdi:memory
        tap_action:
          action: $cmd.poll_start
        hold_action:
          action: $cmd.poll_stop
        poll:
          every_ms: 2000
          action:
            action: $cmd.exec_text
            data:
              cmd: "assets/scripts/ram_usage.sh"
              trim: yes
              max_len: 32
      - name: "GPU"
        presets: [cmd_button]
        icon: mdi:expansion-card-variant
        tap_action:
          action: $cmd.poll_start
        hold_action:
          action: $cmd.poll_stop
        poll:
          every_ms: 2000
          action:
            action: $cmd.exec_text
            data:
              cmd: "assets/scripts/gpu_usage_text.sh"
              trim: yes
              max_len: 32
  apps:
    buttons:
      - name: "Videos"
        presets: [cmd_button]
        icon: mdi:movie-open
        tap_action:
          action: $cmd.exec
          data:
            cmd: "mymedia/miniapp/video_miniapp.sh"
