brightness: 100

sleep:
  dim_brightness: 10
  dim_timeout: 10
  sleep_timeout: 60

system_buttons:
  $page.back:
    position: 11
  $page.previous:
    position: 12
  $page.next:
    position: 13

presets:
  default:
    icon_background_color: "241f31"
    icon_border_radius: 12
    icon_border_width: 1
    icon_border_color: "FFFFFF"
    icon_size: 128
    icon_padding: 0
    icon_offset: 0,0
    icon_brightness: 100
    icon_color: "FFFFFF"
    text_color: "FFFFFF"
    text_align: "bottom"
    text_font: ""
    text_size: 48
    text_offset: 0,0
  $nav:
    icon_background_color: "1a5fb4"
    icon_border_radius: 50
    icon_border_width: 10
    icon_border_color: "FFFFFF"
    icon_size: 128
    icon_padding: 0
    icon_offset: 0,0
    icon_brightness: 100
    icon_color: "FFFFFF"
    text_color: "FFFFFF"
    text_align: "center"
    text_font: ""
    text_size: 48
    text_offset: 0,0
  base_button:
    icon_color: "transparent"
    icon_background_color: "333333"
    icon_size: 128
    icon_border_radius: 12
    icon_border_width: 1
    icon_border_color: "FFFFFF"
  light_off:
    icon: mdi:lightbulb-outline
    icon_background_color: "transparent"
    icon_size: 128
    icon_border_radius: 12
    icon_border_width: 1
    icon_border_color: "FFFFFF"
    icon_color: "transparent"
  light_on:
    icon: mdi:lightbulb
    icon_background_color: "FFD700"
    icon_size: 128
    icon_border_radius: 12
    icon_border_width: 1
    icon_border_color: "FFFFFF"
    icon_color: "transparent"
  screen_off:
    icon: mdi:monitor-off
    icon_background_color: "8b0000"
    icon_size: 128
    icon_border_radius: 12
    icon_border_width: 1
    icon_border_color: "FFFFFF"
    icon_color: "transparent"
  screen_on:
    icon: mdi:monitor
    icon_background_color: "1e90ff"
    icon_size: 128
    icon_border_radius: 12
    icon_border_width: 1
    icon_border_color: "FFFFFF"
    icon_color: "transparent"
  p01:
    icon_background_color: "241f31"
    icon_border_radius: 12
    icon_size: 128
    icon_color: "FFFFFF"
    text_color: "FFFFFF"
    text_align: "bottom"
    text_font: "DejaVuSansMono.ttf"
    text_size: 18
    text_offset: 0,-6
    icon_border_width: 1
    icon_border_color: "FFFFFF"
    icon_padding: 0
    icon_offset: 0,0
    icon_brightness: 99
  p02:
    icon_background_color: "1c71d8"
    icon_border_radius: 12
    icon_size: 128
    icon_color: "FFFFFF"
    text_color: "FFFFFF"
    text_align: "bottom"
    text_font: ""
    text_size: 48
    text_offset: 0,0
    icon_border_width: 8
    icon_border_color: "FFFFFF"
    icon_padding: 60
    icon_offset: 0,0
    icon_brightness: 99
  p03:
    icon_background_color: "813d9c"
    icon_border_radius: 12
    icon_size: 128
    icon_color: "FFFFFF"
    text_color: "FFFFFF"
    text_align: "center"
    text_font: ""
    text_size: 48
    text_offset: 0,0
    icon_border_width: 8
    icon_border_color: "000000"
    icon_padding: 0
    icon_offset: 0,0
    icon_brightness: 99
  p04:
    icon_background_color: "c01c28"
    icon_border_radius: 12
    icon_size: 128
    icon_color: "transparent"
    text_color: "FFFFFF"
    text_align: "bottom"
    text_font: ""
    text_size: 48
    text_offset: 0,-4
    icon_border_width: 12
    icon_border_color: "FFFFFF"
    icon_padding: 0
    icon_offset: 0,0
    icon_brightness: 99
  p05:
    icon_background_color: "e66100"
    icon_border_radius: 12
    icon_size: 160
    icon_color: "FFFFFF"
    text_color: "FFFFFF"
    text_align: "bottom"
    text_font: ""
    text_size: 48
    text_offset: 0,0
    icon_border_width: 1
    icon_border_color: "FFFFFF"
    icon_padding: 0
    icon_offset: -8,0
    icon_brightness: 99
  p06:
    icon_background_color: "f6d32d"
    icon_border_radius: 12
    icon_size: 0
    icon_color: "000000"
    text_color: "000000"
    text_align: "center"
    text_font: "DejaVuSans.ttf"
    text_size: 48
    text_offset: 0,0
    icon_border_width: 10
    icon_border_color: "000000"
    icon_padding: 24
    icon_offset: 0,0
    icon_brightness: 99
  p07:
    icon_background_color: "26a269"
    icon_border_radius: 12
    icon_size: 128
    icon_color: "FFFFFF"
    text_color: "FFFFFF"
    text_align: "bottom"
    text_font: ""
    text_size: 48
    text_offset: 0,0
    icon_border_width: 1
    icon_border_color: "FFFFFF"
    icon_padding: 0
    icon_offset: 0,0
    icon_brightness: 99
  p08:
    icon_background_color: "3584e4"
    icon_border_radius: 18
    icon_size: 128
    icon_color: "FFFFFF"
    text_color: "FFFFFF"
    text_align: "top"
    text_font: ""
    text_size: 48
    text_offset: 0,12
    icon_border_width: 8
    icon_border_color: "transparent"
    icon_padding: 0
    icon_offset: 0,-8
    icon_brightness: 99
  p09:
    icon_background_color: "5e5c64"
    icon_border_radius: 18
    icon_size: 128
    icon_color: "FFFFFF"
    text_color: "FFFFFF"
    text_align: "bottom"
    text_font: ""
    text_size: 48
    text_offset: 0,0
    icon_border_width: 1
    icon_border_color: "FFFFFF"
    icon_padding: 0
    icon_offset: 0,0
    icon_brightness: 99
  p10:
    icon_background_color: "000000"
    icon_border_radius: 18
    icon_size: 128
    icon_color: "FFFFFF"
    text_color: "FFFFFF"
    text_align: "bottom"
    text_font: ""
    text_size: 48
    text_offset: 0,0
    icon_border_width: 10
    icon_border_color: "FFFFFF"
    icon_padding: 0
    icon_offset: 0,0
    icon_brightness: 99
  p11:
    icon_background_color: "2ec27e"
    icon_border_radius: 22
    icon_size: 128
    icon_color: "FFFFFF"
    text_color: "FFFFFF"
    text_align: "bottom"
    text_font: ""
    text_size: 48
    text_offset: 0,0
    icon_border_width: 1
    icon_border_color: "FFFFFF"
    icon_padding: 0
    icon_offset: 0,0
    icon_brightness: 99
  p12:
    icon_background_color: "e01b24"
    icon_border_radius: 22
    icon_size: 128
    icon_color: "FFFFFF"
    text_color: "FFFFFF"
    text_align: "bottom"
    text_font: ""
    text_size: 48
    text_offset: 0,0
    icon_border_width: 1
    icon_border_color: "FFFFFF"
    icon_padding: 0
    icon_offset: 0,0
    icon_brightness: 99
  p13:
    icon_background_color: "1a5fb4"
    icon_border_radius: 22
    icon_size: 128
    icon_color: "FFFFFF"
    text_color: "FFFFFF"
    text_align: "bottom"
    text_font: ""
    text_size: 48
    text_offset: 0,0
    icon_border_width: 1
    icon_border_color: "FFFFFF"
    icon_padding: 0
    icon_offset: 0,0
    icon_brightness: 99
  p14:
    icon_background_color: "613583"
    icon_border_radius: 22
    icon_size: 128
    icon_color: "FFFFFF"
    text_color: "FFFFFF"
    text_align: "bottom"
    text_font: ""
    text_size: 48
    text_offset: 0,0
    icon_border_width: 8
    icon_border_color: "FFFFFF"
    icon_padding: 0
    icon_offset: 0,0
    icon_brightness: 99
  p15:
    icon_background_color: "c64600"
    icon_border_radius: 22
    icon_size: 128
    icon_color: "FFFFFF"
    text_color: "FFFFFF"
    text_align: "bottom"
    text_font: ""
    text_size: 48
    text_offset: 0,0
    icon_border_width: 8
    icon_border_color: "000000"
    icon_padding: 0
    icon_offset: 0,0
    icon_brightness: 99
  p16:
    icon_background_color: "1f9e7a"
    icon_border_radius: 22
    icon_size: 128
    icon_color: "FFFFFF"
    text_color: "FFFFFF"
    text_align: "bottom"
    text_font: ""
    text_size: 48
    text_offset: 0,0
    icon_border_width: 1
    icon_border_color: "FFFFFF"
    icon_padding: 0
    icon_offset: 0,0
    icon_brightness: 99
  p17:
    icon_background_color: "2b6ea3"
    icon_border_radius: 22
    icon_size: 128
    icon_color: "FFFFFF"
    text_color: "FFFFFF"
    text_align: "bottom"
    text_font: ""
    text_size: 48
    text_offset: 0,0
    icon_border_width: 1
    icon_border_color: "FFFFFF"
    icon_padding: 0
    icon_offset: 0,0
    icon_brightness: 99
  p18:
    icon_background_color: "9141ac"
    icon_border_radius: 22
    icon_size: 128
    icon_color: "FFFFFF"
    text_color: "FFFFFF"
    text_align: "bottom"
    text_font: ""
    text_size: 48
    text_offset: 0,0
    icon_border_width: 1
    icon_border_color: "FFFFFF"
    icon_padding: 0
    icon_offset: 0,0
    icon_brightness: 99
  p19:
    icon_background_color: "a51d2d"
    icon_border_radius: 22
    icon_size: 128
    icon_color: "FFFFFF"
    text_color: "FFFFFF"
    text_align: "bottom"
    text_font: ""
    text_size: 48
    text_offset: 0,0
    icon_border_width: 1
    icon_border_color: "FFFFFF"
    icon_padding: 0
    icon_offset: 0,0
    icon_brightness: 99
  p20:
    icon_background_color: "c64600"
    icon_border_radius: 22
    icon_size: 128
    icon_color: "FFFFFF"
    text_color: "FFFFFF"
    text_align: "bottom"
    text_font: ""
    text_size: 48
    text_offset: 0,0
    icon_border_width: 1
    icon_border_color: "FFFFFF"
    icon_padding: 0
    icon_offset: 0,0
    icon_brightness: 99
  p21:
    icon_background_color: "e5a50a"
    icon_border_radius: 22
    icon_size: 128
    icon_color: "000000"
    text_color: "000000"
    text_align: "bottom"
    text_font: ""
    text_size: 48
    text_offset: 0,0
    icon_border_width: 1
    icon_border_color: "FFFFFF"
    icon_padding: 0
    icon_offset: 0,0
    icon_brightness: 99
  p22:
    icon_background_color: "26a269"
    icon_border_radius: 22
    icon_size: 128
    icon_color: "FFFFFF"
    text_color: "FFFFFF"
    text_align: "bottom"
    text_font: ""
    text_size: 48
    text_offset: 0,0
    icon_border_width: 1
    icon_border_color: "FFFFFF"
    icon_padding: 0
    icon_offset: 0,0
    icon_brightness: 99
  p23:
    icon_background_color: "3584e4"
    icon_border_radius: 22
    icon_size: 128
    icon_color: "FFFFFF"
    text_color: "FFFFFF"
    text_align: "bottom"
    text_font: ""
    text_size: 48
    text_offset: 0,0
    icon_border_width: 1
    icon_border_color: "FFFFFF"
    icon_padding: 0
    icon_offset: 0,0
    icon_brightness: 99
  p24:
    icon_background_color: "5e5c64"
    icon_border_radius: 22
    icon_size: 128
    icon_color: "FFFFFF"
    text_color: "FFFFFF"
    text_align: "bottom"
    text_font: ""
    text_size: 48
    text_offset: 0,0
    icon_border_width: 1
    icon_border_color: "FFFFFF"
    icon_padding: 0
    icon_offset: 0,0
    icon_brightness: 99
  p25:
    icon_background_color: "241f31"
    icon_border_radius: 22
    icon_size: 128
    icon_color: "FFFFFF"
    text_color: "FFFFFF"
    text_align: "bottom"
    text_font: ""
    text_size: 48
    text_offset: 0,0
    icon_border_width: 1
    icon_border_color: "FFFFFF"
    icon_padding: 0
    icon_offset: 0,0
    icon_brightness: 99
  p26:
    icon_background_color: "1c71d8"
    icon_border_radius: 22
    icon_size: 128
    icon_color: "FFFFFF"
    text_color: "FFFFFF"
    text_align: "bottom"
    text_font: ""
    text_size: 48
    text_offset: 0,0
    icon_border_width: 1
    icon_border_color: "FFFFFF"
    icon_padding: 0
    icon_offset: 0,0
    icon_brightness: 99
  p27:
    icon_background_color: "813d9c"
    icon_border_radius: 22
    icon_size: 128
    icon_color: "FFFFFF"
    text_color: "FFFFFF"
    text_align: "bottom"
    text_font: ""
    text_size: 48
    text_offset: 0,0
    icon_border_width: 1
    icon_border_color: "FFFFFF"
    icon_padding: 0
    icon_offset: 0,0
    icon_brightness: 99
  p28:
    icon_background_color: "c01c28"
    icon_border_radius: 22
    icon_size: 128
    icon_color: "FFFFFF"
    text_color: "FFFFFF"
    text_align: "bottom"
    text_font: ""
    text_size: 48
    text_offset: 0,0
    icon_border_width: 1
    icon_border_color: "FFFFFF"
    icon_padding: 0
    icon_offset: 0,0
    icon_brightness: 99
  p29:
    icon_background_color: "e66100"
    icon_border_radius: 22
    icon_size: 128
    icon_color: "FFFFFF"
    text_color: "FFFFFF"
    text_align: "bottom"
    text_font: ""
    text_size: 48
    text_offset: 0,0
    icon_border_width: 1
    icon_border_color: "FFFFFF"
    icon_padding: 0
    icon_offset: 0,0
    icon_brightness: 99
  p30:
    icon_background_color: "26a269"
    icon_border_radius: 22
    icon_size: 128
    icon_color: "FFFFFF"
    text_color: "FFFFFF"
    text_align: "bottom"
    text_font: ""
    text_size: 48
    text_offset: 0,0
    icon_border_width: 1
    icon_border_color: "FFFFFF"
    icon_padding: 0
    icon_offset: 0,0
    icon_brightness: 99

  dir1:
    icon_background_color: "1a5fb4"
    icon_border_radius: 20
    icon_border_width: 8
    icon_border_color: "FFFFFF"
    icon_size: 128
    icon_padding: 0
    icon_offset: 0,0
    icon_brightness: 99
    icon_color: "FFFFFF"
    text_color: "FFFFFF"
    text_align: "bottom"
    text_font: ""
    text_size: 48
    text_offset: 0,0
  dir2:
    icon_background_color: "813d9c"
    icon_border_radius: 20
    icon_border_width: 8
    icon_border_color: "FFFFFF"
    icon_size: 128
    icon_padding: 0
    icon_offset: 0,0
    icon_brightness: 99
    icon_color: "FFFFFF"
    text_color: "FFFFFF"
    text_align: "bottom"
    text_font: ""
    text_size: 48
    text_offset: 0,0
  dir3:
    icon_background_color: "c01c28"
    icon_border_radius: 20
    icon_border_width: 8
    icon_border_color: "FFFFFF"
    icon_size: 128
    icon_padding: 0
    icon_offset: 0,0
    icon_brightness: 99
    icon_color: "FFFFFF"
    text_color: "FFFFFF"
    text_align: "bottom"
    text_font: ""
    text_size: 48
    text_offset: 0,0

pages:
  $root:
    buttons:
      - name: "Salon"
        presets: [dir2]
        icon: mdi:folder-star-outline
        text: "SALON"
        tap_action:
          action: $page.go_to
          data: "salon"
      - name: "Scripts"
        presets: [dir1]
        icon: mdi:folder-outline
        text: "SCRIPTS"
        tap_action:
          action: $page.go_to
          data: "scripts"
      - name: "Settings"
        presets: [dir3]
        icon: mdi:folder-multiple-outline
        text: "SETTINGS"
        tap_action:
          action: $page.go_to
          data: "settings"
      - name: "Item 04"
        presets: [p04]
        icon: mdi:numeric-4-circle
        text: "CUTOUT"
      - name: "Item 05"
        presets: [p05]
        icon: mdi:numeric-5-circle
      - name: "Item 06"
        presets: [p06]
        text: "TEXT_ONLY"
      - name: "Item 07"
        presets: [p07]
      - name: "Item 08"
        presets: [p08]
        icon: mdi:numeric-8-circle
        text: "TOP"
      - name: "Item 09"
        presets: [p09]
        icon: mdi:numeric-9-circle
      - name: "Item 10"
        presets: [p10]
        icon: mdi:numeric-0-circle
      - name: "Item 11"
        presets: [p11]
        icon: mdi:star
      - name: "Item 12"
        presets: [p12]
        icon: mdi:heart-outline
      - name: "Item 13"
        presets: [p13]
        icon: mdi:home-outline
      - name: "Item 14"
        presets: [p14]
        icon: mdi:cog-outline
      - name: "Item 15"
        presets: [p15]
        icon: mdi:account-outline
      - name: "Item 16"
        presets: [p16]
        icon: mdi:bell-outline
      - name: "Item 17"
        presets: [p17]
        icon: mdi:calendar-outline
      - name: "Item 18"
        presets: [p18]
        icon: mdi:camera-outline
      - name: "Item 19"
        presets: [p19]
        icon: mdi:chart-line
      - name: "Item 20"
        presets: [p20]
        icon: mdi:cloud-outline
      - name: "Item 21"
        presets: [p21]
        icon: mdi:dev-to
      - name: "Item 22"
        presets: [p22]
        icon: mdi:database-outline
      - name: "Item 23"
        presets: [p23]
        icon: mdi:download-outline
      - name: "Item 24"
        presets: [p24]
        icon: mdi:email-outline
      - name: "Item 25"
        presets: [p25]
        icon: mdi:file-document-outline
      - name: "Item 26"
        presets: [p26]
        icon: mdi:folder-outline
      - name: "Item 27"
        presets: [p27]
        icon: mdi:format-list-bulleted
      - name: "Item 28"
        presets: [p28]
        icon: mdi:map-outline
      - name: "Item 29"
        presets: [p29]
        icon: mdi:music-note-outline
      - name: "Item 30"
        presets: [p30]
        icon: mdi:power

  scripts:
    buttons:
      - name: "Tool 2"
        presets: [p12]
        icon: mdi:dev-to
        text: "HA"
      - name: "Tool 2"
        presets: [p12]
        icon: mdi:dev-to
        text: "HA"
      - name: "Deep"
        presets: [p30]
        icon: mdi:dev-to
        text: "DEEP"
        tap_action:
          action: $page.go_to
          data: "scripts_deep"

  scripts_deep:
    buttons:
      - name: "Leaf"
        presets: [dir1]
        icon: mdi:leaf
        text: "LEAF"
      - name: "Up"
        presets: [dir1]
        icon: mdi:arrow-up-bold
        text: "UP"

  salon:
    buttons:
      - name: "Lampe droite"
        entity_id: light.lampe_droite
        presets: [base_button]
        tap_action:
          action: light.toggle
        states:
          "on":
            name: "LD ON"
            presets: [light_on]
          "off":
            name: "LD OFF"
            presets: [light_off]
      - name: "Lampe gauche"
        entity_id: light.lampe_gauche
        presets: [base_button]
        tap_action:
          action: light.toggle
        states:
          "on":
            name: "LG ON"
            presets: [light_on]
          "off":
            name: "LG OFF"
            presets: [light_off]
      - name: "Lampe escalier"
        entity_id: light.lampe_escalier
        presets: [base_button]
        tap_action:
          action: light.toggle
        states:
          "on":
            name: "LE ON"
            presets: [light_on]
          "off":
            name: "LE OFF"
            presets: [light_off]
      - name: "Écrans Salon"
        entity_id: script.eteint_les_ecrans_du_salon
        presets: [base_button]
        tap_action:
          action: script.eteint_les_ecrans_du_salon
        states:
          "on":
            name: "Écrans éteints"
            presets: [screen_on]
          "off":
            name: "Écrans allumés"
            presets: [screen_off]
      - name: "Temperature"
        entity_id: sensor.tz3000_utwgoauk_snzb_02_temperature
        presets: [base_button]


  settings:
    buttons:
      - name: "Home"
        presets: [p13]
        icon: mdi:home-outline
        text: "HOME"
      - name: "Cloud"
        presets: [p20]
        icon: mdi:cloud-outline
        text: "CLD"
      - name: "Map"
        presets: [p28]
        icon: mdi:map-outline
        text: "MAP"
      - name: "Map"
        presets: [p28]
        icon: mdi:map-outline
        text: "MAP"
